name: CI

on:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - run: echo "Deploying because this is the main branch"
