env:
  APP_NAME: my_app
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - names: show them
        env:
          GREETING: hello
       run: echo "Deploying Jobs"
